# ?? Attention :
# Les identifiants de connexion fournis dans ce projet sont exclusivement réservés à un usage local, pour l'essai et la validation du projet.
# Ils ne doivent en aucun cas être utilisés en production ou pour des données sensibles.

spring.application.name=ChaTop
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081
spring.config.import=optional:file:.env[.properties]

# Taille max d?un fichier
spring.servlet.multipart.max-file-size=10MB

# Taille max de la requête multipart
spring.servlet.multipart.max-request-size=10MB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}